@FECHA_DESDE DATETIME, 
@FECHA_HASTA DATETIME,
@Selección_de_Usuarios_por_Usuario SINO_FILT, @Usuario_FILTRO USUARIO_ALL

AS


IF @Fecha_Desde > @Fecha_Hasta
    BEGIN
        RAISERROR ('__TRANSLATE__DateToDateSince', 16, 1, 1, 1, 1)
        RETURN
    END

    DECLARE @intDoc1 INT

    CREATE TABLE #USUARIOS (USUARIO VARCHAR(5))

    
    IF @Selección_de_Usuarios_por_Usuario = 'S'
    BEGIN
        EXEC sp_xml_preparedocument @intDoc1 OUTPUT, @Usuario_FILTRO
    
        INSERT INTO #USUARIOS
        SELECT usuario = usuario
        FROM OPENXML(@intDoc1, '/NewDataSet/Valores')
        WITH (usuario varchar(5) 'Valor')
    
        EXEC sp_xml_removedocument @intDoc1
        
        IF NOT EXISTS (SELECT * FROM #USUARIOS)
        BEGIN
            RAISERROR ('__TRANSLATE__MustSelectUser', 16, 1, 1, 1, 1)
            RETURN
        END
        
    END

    CREATE TABLE #AGENDAS (USUARIO VARCHAR(MAX),IDINTERNO VARCHAR(MAX),[GENERACION AGENDA] VARCHAR(MAX),[AGENDA] VARCHAR(MAX),
                        ESTADO VARCHAR(MAX),[RESOLUCION] VARCHAR(MAX),ORDEN INT)

    CREATE TABLE #HISTORIAL (IDINTERNO VARCHAR(MAX),TS VARCHAR (MAX),
                            RELLAMAR VARCHAR(MAX),USUARIO VARCHAR(MAX),
                            SUBCATEGORIA VARCHAR(MAX),MOTIVO VARCHAR(MAX)
                            ,ORDEN INT)


    IF(@Selección_de_Usuarios_por_Usuario='S')
    BEGIN

    -- INSERT INTO #HISTORIAL (IDINTERNO,TS,RELLAMAR,SUBCATEGORIA,ORDEN,USUARIO,MOTIVO)
    -- SELECT 
    -- D.IDINTERNO,
    -- CONVERT(VARCHAR(19),D.TS,121),
    -- CONVERT(VARCHAR(19),D.RELLAMAR,121),
    -- D.SUBCATEGORIA,
    -- ROW_NUMBER() OVER(PARTITION BY idinterno ORDER BY idinterno),
    -- D.USUARIO,
    -- D.MOTIVO_TRAIDA

    -- FROM CONTACTOS_DETALLE D(NOLOCK)
    -- INNER JOIN #USUARIOS US
    -- ON US.USUARIO=D.USUARIO
    -- WHERE TS BETWEEN @FECHA_DESDE AND @FECHA_HASTA
    -- ORDER BY TS ASC

        INSERT INTO #HISTORIAL (IDINTERNO, TS, RELLAMAR, SUBCATEGORIA, ORDEN, USUARIO, MOTIVO)
        SELECT 
            CD.IDINTERNO,
            CASE
                WHEN EXISTS (
                    SELECT 1
                    FROM CONTACTOS_DETALLE CD2
                    WHERE CD2.IDINTERNO = CD.IDINTERNO
                    AND CD2.TS >= CD.RELLAMAR
                )
                THEN (
                    SELECT 
                    CONVERT(VARCHAR(19),MIN(TS),121)
                    
                    FROM CONTACTOS_DETALLE CD3
                    WHERE CD3.IDINTERNO = CD.IDINTERNO
                    AND CD3.TS >= CD.RELLAMAR
                )
                ELSE CONVERT(VARCHAR(19),CD.TS,121)
            END AS TS,
            CONVERT(VARCHAR(19), CD.RELLAMAR, 120),
            CD.SUBCATEGORIA,
            ROW_NUMBER() OVER (PARTITION BY CD.IDINTERNO ORDER BY CD.IDINTERNO),
            CD.USUARIO,
            CD.MOTIVO_TRAIDA
        FROM CONTACTOS_DETALLE CD (NOLOCK)
        WHERE CD.TS BETWEEN @FECHA_DESDE AND @FECHA_HASTA
        ORDER BY TS ASC;


    INSERT INTO #AGENDAS (USUARIO,IDINTERNO,[GENERACION AGENDA],AGENDA,ORDEN)
    SELECT USUARIO,IDINTERNO,TS,RELLAMAR,ORDEN
    FROM #HISTORIAL (NOLOCK)
    WHERE SUBCATEGORIA IN (
    SELECT SUBCATEGORIA FROM SUBCATEGORIAS (NOLOCK)
    WHERE ACCION='RELLAMAR' AND TIPO_RELLAMADA='AG')


    SELECT 
        A.IDINTERNO,
        A.[GENERACION AGENDA],
        A.AGENDA,
        CONVERT(VARCHAR(300),HORDEN.USUARIO)+' - '+U.NOMBRE+' '+U.APELLIDO AS USUARIO,
        -- CASE WHEN (DATEDIFF(day,HORDEN.TS,A.AGENDA)>0)THEN 'NO CUMPLIDA' ELSE 'CUMPLIDA' END AS ESTADO,
        CASE 
            WHEN (CAST(A.[GENERACION AGENDA] AS DATETIME) <= CAST(A.AGENDA AS DATETIME)) AND 
            (CAST(GETDATE() AS DATETIME) < CAST(A.AGENDA AS DATETIME)) THEN 'PENDIENTE'
            WHEN CAST(A.[GENERACION AGENDA] AS DATE) = CAST(A.AGENDA AS DATE) THEN 'CUMPLIDA'
            ELSE 'INCUMPLIDA'
        END AS ESTADO,
        -- AND CAST(A.AGENDA AS DATE) < CAST(GETDATE() AS DATE)
        CONVERT(VARCHAR(300),HORDEN.SUBCATEGORIA)+' - '+S.DESCRIPCION AS SUBCATEGORIA
    FROM #AGENDAS A
    INNER JOIN 
    (
        
        SELECT ORDEN AS ORDEN,
            IDINTERNO AS IDINTERNO ,
            TS AS TS,
            -- RELLAMAR AS TS,
            USUARIO AS USUARIO,
            SUBCATEGORIA AS SUBCATEGORIA
        FROM #HISTORIAL H
        WHERE /*H.IDINTERNO='656679' AND*/ H.ORDEN IN (SELECT A.ORDEN+1 FROM #HISTORIAL H
        INNER JOIN #AGENDAS A 
        ON H.IDINTERNO=A.IDINTERNO and h.ORDEN=a.ORDEN)
    )HORDEN
    ON A.IDINTERNO=HORDEN.IDINTERNO 
    LEFT JOIN TEL_CALLCENTER.._USUARIOS U (NOLOCK)
    ON A.USUARIO=U.USUARIO
    LEFT JOIN SUBCATEGORIAS S (NOLOCK)
    ON HORDEN.SUBCATEGORIA=S.SUBCATEGORIA
    INNER JOIN #USUARIOS US
    ON US.USUARIO=A.USUARIO
    where HORDEN.ORDEN=a.ORDEN+1 and a.AGENDA<>'9999-12-31 23:59:59'
    -- where HORDEN.ORDEN=a.ORDEN+1 and DATE(a.AGENDA)<>'9999-12-31'
    -- WHERE HORDEN.ORDEN = a.ORDEN + 1 AND CAST(a.AGENDA AS DATE) <> '9999-12-31'

    UNION ALL

    SELECT '','','','','',''
    UNION ALL
    SELECT 'TOTAL DE AGENDAS POR USUARIO','','','','',''
    UNION ALL
    SELECT 
        CONVERT(VARCHAR(200),A.USUARIO)+' - '+U.NOMBRE+' '+U.APELLIDO AS USUARIO,
        CONVERT(VARCHAR(300),COUNT(A.USUARIO)) AS [CANTIDAD DE AGENDAS],
        '',
        '',
        '',
        ''
    FROM #AGENDAS A (NOLOCK) 
    INNER JOIN TEL_CALLCENTER.._USUARIOS U(NOLOCK)
    ON A.USUARIO=U.USUARIO
    INNER JOIN #USUARIOS US
    ON US.USUARIO=A.USUARIO
    GROUP BY A.USUARIO,U.NOMBRE,U.APELLIDO

    END 

ELSE
    BEGIN

    -- INSERT INTO #HISTORIAL (IDINTERNO,TS,RELLAMAR,SUBCATEGORIA,ORDEN,USUARIO,MOTIVO)
    -- SELECT 
    --         IDINTERNO,
    --         CONVERT(VARCHAR(19),TS,121),
    --         CONVERT(VARCHAR(19),RELLAMAR,121),
    --         SUBCATEGORIA,
    --         ROW_NUMBER() OVER(PARTITION BY idinterno ORDER BY idinterno),
    --         USUARIO,
    --         MOTIVO_TRAIDA
    -- FROM CONTACTOS_DETALLE (NOLOCK)
    -- WHERE TS BETWEEN @FECHA_DESDE AND @FECHA_HASTA
    -- ORDER BY TS ASC
    INSERT INTO #HISTORIAL (IDINTERNO, TS, RELLAMAR, SUBCATEGORIA, ORDEN, USUARIO, MOTIVO)
    SELECT 
        CD.IDINTERNO,
        CASE
            WHEN EXISTS (
                SELECT 1
                FROM CONTACTOS_DETALLE CD2
                WHERE CD2.IDINTERNO = CD.IDINTERNO
                AND CD2.TS >= CD.RELLAMAR
            )
            THEN (
                SELECT 
                CONVERT(VARCHAR(19),MIN(TS),121)
                
                FROM CONTACTOS_DETALLE CD3
                WHERE CD3.IDINTERNO = CD.IDINTERNO
                AND CD3.TS >= CD.RELLAMAR
            )
            ELSE CONVERT(VARCHAR(19),CD.TS,121)
        END AS TS,
        CONVERT(VARCHAR(19), CD.RELLAMAR, 120),
        CD.SUBCATEGORIA,
        ROW_NUMBER() OVER (PARTITION BY CD.IDINTERNO ORDER BY CD.IDINTERNO),
        CD.USUARIO,
        CD.MOTIVO_TRAIDA
    FROM CONTACTOS_DETALLE CD (NOLOCK)
    WHERE CD.TS BETWEEN @FECHA_DESDE AND @FECHA_HASTA
    ORDER BY TS ASC;


    INSERT INTO #AGENDAS (USUARIO,IDINTERNO,[GENERACION AGENDA],AGENDA,ORDEN)
    SELECT USUARIO,IDINTERNO,TS,RELLAMAR,ORDEN
    FROM #HISTORIAL (NOLOCK)
    WHERE SUBCATEGORIA IN (
    SELECT SUBCATEGORIA FROM SUBCATEGORIAS (NOLOCK)
    WHERE ACCION='RELLAMAR' AND TIPO_RELLAMADA='AG')




        
        
    SELECT 
        A.IDINTERNO,
        A.[GENERACION AGENDA],
        A.AGENDA,
        CONVERT(VARCHAR(300),HORDEN.USUARIO)+' - '+U.NOMBRE+' '+U.APELLIDO AS USUARIO,
        -- CASE WHEN (DATEDIFF(day,HORDEN.TS,A.AGENDA)>0)THEN 'NO CUMPLIDA' ELSE 'CUMPLIDA' END AS ESTADO,

        --                      ts                          rellamar
        CASE 
            WHEN (CAST(A.[GENERACION AGENDA] AS DATETIME) <= CAST(A.AGENDA AS DATETIME)) AND 
            (CAST(GETDATE() AS DATETIME) < CAST(A.AGENDA AS DATETIME)) THEN 'PENDIENTE'
            WHEN CAST(A.[GENERACION AGENDA] AS DATE) = CAST(A.AGENDA AS DATE) THEN 'CUMPLIDA'
            ELSE 'INCUMPLIDA'
        END AS ESTADO,
        CONVERT(VARCHAR(300),HORDEN.SUBCATEGORIA)+' - '+S.DESCRIPCION AS SUBCATEGORIA
    FROM #AGENDAS A
    INNER JOIN 
    (
        SELECT ORDEN AS ORDEN,
        IDINTERNO AS IDINTERNO ,
        TS AS TS,
        -- RELLAMAR AS TS,
        USUARIO AS USUARIO,
        SUBCATEGORIA AS SUBCATEGORIA
        FROM #HISTORIAL H
        WHERE /*H.IDINTERNO='656679' AND*/ H.ORDEN IN (SELECT A.ORDEN+1 FROM #HISTORIAL H
        INNER JOIN #AGENDAS A 
        ON H.IDINTERNO=A.IDINTERNO and h.ORDEN=a.ORDEN)
    )HORDEN
    ON A.IDINTERNO=HORDEN.IDINTERNO 
    LEFT JOIN TEL_CALLCENTER.._USUARIOS U (NOLOCK)
    ON A.USUARIO=U.USUARIO
    LEFT JOIN SUBCATEGORIAS S (NOLOCK)
    ON HORDEN.SUBCATEGORIA=S.SUBCATEGORIA
    where HORDEN.ORDEN=a.ORDEN+1 and a.AGENDA<>'9999-12-31 23:59:59'
    -- where HORDEN.ORDEN=a.ORDEN+1 and DATE(a.AGENDA)<>'9999-12-31'
    -- WHERE HORDEN.ORDEN = a.ORDEN + 1 AND CAST(a.AGENDA AS DATE) <> '9999-12-31'


    UNION ALL

    SELECT '','','','','',''
    UNION ALL
    SELECT 'TOTAL DE AGENDAS POR USUARIO','','','','',''
    UNION ALL
    SELECT 
    CONVERT(VARCHAR(200),A.USUARIO)+' - '+U.NOMBRE+' '+U.APELLIDO AS USUARIO,
    CONVERT(VARCHAR(300),COUNT(A.USUARIO)) AS [CANTIDAD DE AGENDAS],
    '',
    '',
    '',
    ''
    FROM #AGENDAS A (NOLOCK) 
    INNER JOIN TEL_CALLCENTER.._USUARIOS U(NOLOCK)
    ON A.USUARIO=U.USUARIO
    GROUP BY A.USUARIO,U.NOMBRE,U.APELLIDO
END
